[package]
name = "tiny-raytracer"
version = "0.1.0"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.1"
nalgebra = "0.17.0"
png = "0.14.0"
rayon = "1.0.3"
